# Generated by Django 4.2.3 on 2023-08-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.IntegerField()),
                ('request_to', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='city not set', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='college not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='digit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='myId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rltn',
            field=models.CharField(default='relationship status hidden', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together={('self_id', 'friend_id')},
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.CheckConstraint(check=models.Q(('self_id', models.F('friend_id')), _negated=True), name='not_equal_value'),
        ),
        migrations.AddConstraint(
            model_name='friendrequests',
            constraint=models.CheckConstraint(check=models.Q(('request_from', models.F('request_to')), _negated=True), name='not_equal_values'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrequests',
            unique_together={('request_from', 'request_to')},
        ),
    ]
