# Generated by Django 4.2.3 on 2023-08-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='city not set', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='college not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='digit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='myId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='rltn',
            field=models.CharField(default='relationship status hidden', max_length=25),
        ),
    ]
