# Generated by Django 4.2.3 on 2023-08-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_user_latitude_remove_user_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='myId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
