# Generated by Django 4.2.3 on 2023-08-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendrequests_remove_user_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='myId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
