# Generated by Django 4.2.3 on 2023-08-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_user_myid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_integer', models.IntegerField()),
                ('second_integer', models.IntegerField()),
            ],
        ),
    ]
