# Generated by Django 4.2.3 on 2023-07-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_remove_posts_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='self_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
