# Generated by Django 4.2.3 on 2023-08-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_friendrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequests',
            old_name='first_integer',
            new_name='request_from',
        ),
        migrations.RenameField(
            model_name='friendrequests',
            old_name='second_integer',
            new_name='request_to',
        ),
    ]
