# Generated by Django 4.2.3 on 2023-07-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_posts_self_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
    ]
